// Adal Works site runtime: i18n, navigation, attribution capture and the quote form.
// Texts live in /i18n/<page>.js (generated by _build/build.py from _build/content.py).
const dictionary = window.ADAL_I18N || { ru: {}, kz: {}, en: {} };

const WHATSAPP_NUMBER = '77003330999';
const languageStorageKey = 'adalworks-language';
const attributionKey = 'adalworks-attribution';
const locales = { ru: 'ru_KZ', kz: 'kk_KZ', en: 'en_US' };
const defaultLanguage = dictionary[document.documentElement.dataset.defaultLang] ? document.documentElement.dataset.defaultLang : 'kz';
const has = (object, key) => Object.prototype.hasOwnProperty.call(object, key);

const menuButton = document.querySelector('[data-menu-button]');
const mobileMenu = document.querySelector('[data-mobile-menu]');
const languageButtons = document.querySelectorAll('[data-lang]');
const quoteForms = [];
let activeLanguage = defaultLanguage;

const languageFromTag = (tag) => {
  if (typeof tag !== 'string') return '';
  const primary = tag.trim().toLowerCase().split(/[-_]/)[0];
  if (primary === 'ru') return 'ru';
  if (primary === 'en') return 'en';
  if (primary === 'kk' || primary === 'kz') return 'kz';
  return '';
};

const detectLanguage = () => {
  const tags = [];
  if (typeof navigator !== 'undefined') {
    const list = navigator.languages;
    if (list && typeof list !== 'string' && typeof list.length === 'number') {
      for (let index = 0; index < list.length; index += 1) tags.push(list[index]);
    }
    if (typeof navigator.language === 'string') tags.push(navigator.language);
  }
  for (const tag of tags) {
    const match = languageFromTag(tag);
    if (match) return match;
  }
  return defaultLanguage;
};

const readSavedLanguage = () => {
  try {
    const saved = localStorage.getItem(languageStorageKey);
    return dictionary[saved] ? saved : '';
  } catch {
    return '';
  }
};

const saveLanguage = (lang) => {
  try {
    localStorage.setItem(languageStorageKey, lang);
  } catch {
    // The choice still applies for this visit when storage is blocked.
  }
};

const setMetaContent = (selector, value) => {
  const node = document.querySelector(selector);
  if (node && value) node.setAttribute('content', value);
};

const whatsappUrl = (message) => `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;

const setLanguage = (lang, { persist = false } = {}) => {
  const active = dictionary[lang] ? lang : defaultLanguage;
  const copy = dictionary[active];
  activeLanguage = active;
  document.documentElement.lang = active === 'kz' ? 'kk' : active;
  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const key = node.dataset.i18n;
    if (!has(copy, key)) return;
    node.textContent = copy[key];
    if (copy[key] === '') node.setAttribute('hidden', '');
    else node.removeAttribute('hidden');
  });
  document.querySelectorAll('[data-i18n-aria]').forEach((node) => {
    const key = node.dataset.i18nAria;
    if (has(copy, key)) node.setAttribute('aria-label', copy[key]);
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((node) => {
    const key = node.dataset.i18nPlaceholder;
    if (has(copy, key)) node.setAttribute('placeholder', copy[key]);
  });
  document.querySelectorAll('[data-i18n-alt]').forEach((node) => {
    const key = node.dataset.i18nAlt;
    if (has(copy, key)) node.setAttribute('alt', copy[key]);
  });
  if (copy.pageTitle) document.title = copy.pageTitle;
  setMetaContent('meta[name="description"]', copy.pageDescription);
  setMetaContent('meta[property="og:title"]', copy.pageTitle);
  setMetaContent('meta[property="og:description"]', copy.pageDescription);
  setMetaContent('meta[property="og:locale"]', locales[active]);
  setMetaContent('meta[name="twitter:title"]', copy.pageTitle);
  setMetaContent('meta[name="twitter:description"]', copy.pageDescription);
  const schemaNode = document.querySelector('script[type="application/ld+json"]');
  if (schemaNode && copy.schemaDescription) {
    try {
      const data = JSON.parse(schemaNode.textContent);
      data.description = copy.schemaDescription;
      schemaNode.textContent = JSON.stringify(data, null, 2);
    } catch {
      // Keep the static schema if the block cannot be parsed.
    }
  }
  languageButtons.forEach((button) => {
    const isActive = button.dataset.lang === active;
    button.classList.toggle('is-active', isActive);
    button.setAttribute('aria-pressed', String(isActive));
  });
  document.querySelectorAll('[data-whatsapp]').forEach((link) => {
    const messageKey = link.getAttribute('data-i18n-whatsapp');
    const message = messageKey && has(copy, messageKey) ? copy[messageKey] : copy.whatsappText;
    link.href = whatsappUrl(message || '');
    link.setAttribute('target', '_blank');
    link.setAttribute('rel', 'noopener');
  });
  quoteForms.forEach((form) => form.refresh());
  if (persist) saveLanguage(active);
};

// ------------------------------------------------------------- navigation
const closeMobileMenu = () => {
  mobileMenu?.classList.remove('is-open');
  document.body.classList.remove('menu-open');
  menuButton?.setAttribute('aria-expanded', 'false');
};

menuButton?.addEventListener('click', () => {
  const isOpen = mobileMenu.classList.toggle('is-open');
  document.body.classList.toggle('menu-open', isOpen);
  menuButton.setAttribute('aria-expanded', String(isOpen));
});

mobileMenu?.querySelectorAll('a').forEach((link) => link.addEventListener('click', closeMobileMenu));

document.addEventListener('keydown', (event) => {
  if (event.key === 'Escape' && mobileMenu?.classList.contains('is-open')) {
    closeMobileMenu();
    menuButton?.focus();
  }
});

document.querySelectorAll('[data-dropdown]').forEach((dropdown) => {
  const button = dropdown.querySelector('[data-dropdown-button]');
  const setOpen = (open) => {
    dropdown.classList.toggle('is-open', open);
    button.setAttribute('aria-expanded', String(open));
  };
  button.addEventListener('click', () => setOpen(!dropdown.classList.contains('is-open')));
  document.addEventListener('click', (event) => {
    if (!dropdown.contains(event.target)) setOpen(false);
  });
  dropdown.addEventListener('keydown', (event) => {
    if (event.key === 'Escape') {
      setOpen(false);
      button.focus();
    }
  });
  dropdown.addEventListener('focusout', (event) => {
    if (!dropdown.contains(event.relatedTarget)) setOpen(false);
  });
});

languageButtons.forEach((button) => {
  button.addEventListener('click', () => setLanguage(button.dataset.lang, { persist: true }));
});

const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) entry.target.classList.add('is-visible');
    });
  },
  { threshold: 0.12 }
);

document.querySelectorAll('.section, .stats, .contact').forEach((node) => {
  node.classList.add('reveal');
  observer.observe(node);
});

// ------------------------------------------------------------- attribution (UTM / gclid)
const attributionParams = ['utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content', 'gclid', 'yclid'];

const captureAttribution = () => {
  try {
    const params = new URLSearchParams(window.location.search);
    const found = {};
    attributionParams.forEach((name) => {
      const value = params.get(name);
      if (value) found[name] = value.trim().slice(0, 150);
    });
    if (Object.keys(found).length) sessionStorage.setItem(attributionKey, JSON.stringify(found));
  } catch {
    // Attribution is optional.
  }
};

const attributionTag = () => {
  let data = {};
  try {
    data = JSON.parse(sessionStorage.getItem(attributionKey) || '{}') || {};
  } catch {
    data = {};
  }
  const path = ['utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content'].map((key) => data[key]).filter(Boolean);
  const parts = [];
  if (path.length) parts.push(path.join('/'));
  if (data.gclid) parts.push(`gclid=${data.gclid}`);
  if (data.yclid) parts.push(`yclid=${data.yclid}`);
  return parts.length ? `ref: ${parts.join(' ')}` : '';
};

// ------------------------------------------------------------- quote form
const normalizePhone = (raw) => {
  const value = String(raw || '').trim();
  if (/[a-zа-яё]/i.test(value)) return null;
  const digits = value.replace(/\D/g, '');
  let local = '';
  if (/^8\d{10}$/.test(digits)) local = digits.slice(1);
  else if (/^7\d{10}$/.test(digits)) local = digits.slice(1);
  else if (/^7\d{9}$/.test(digits)) local = digits;
  if (local) {
    return `+7 ${local.slice(0, 3)} ${local.slice(3, 6)} ${local.slice(6, 8)} ${local.slice(8, 10)}`;
  }
  if (value.startsWith('+') && digits.length >= 10 && digits.length <= 15 && !digits.startsWith('7')) return `+${digits}`;
  return null;
};

const positiveInteger = (value) => /^\d{1,7}$/.test(value) && Number(value) > 0;
const nonNegativeInteger = (value) => /^\d{1,7}$/.test(value);

const initQuoteForm = (form) => {
  const steps = [...form.querySelectorAll('[data-step]')];
  const progress = [...form.querySelectorAll('[data-progress]')];
  const summary = form.querySelector('[data-error-summary]');
  const done = form.querySelector('[data-quote-done]');
  const doneLink = form.querySelector('[data-done-link]');
  const requiredNote = form.querySelector('.quote-required-note');
  let current = 1;
  let lastUrl = '';

  const copy = () => dictionary[activeLanguage] || {};
  const checkedValue = (name) => form.querySelector(`input[name="${name}"]:checked`)?.value || '';
  // A field counts when its conditional group is shown; the step itself may be hidden (e.g. on submit).
  const isActiveField = (field) => !field.closest('[data-show-for][hidden], [data-hide-once][hidden]');

  const updateConditional = () => {
    const type = checkedValue('type');
    const once = checkedValue('frequency') === 'once';
    form.querySelectorAll('[data-show-for]').forEach((group) => {
      group.hidden = !group.dataset.showFor.split(' ').includes(type);
    });
    form.querySelectorAll('[data-hide-once]').forEach((field) => {
      field.hidden = once;
    });
    form.querySelectorAll('input, select, textarea').forEach((control) => {
      const step = control.closest('[data-step]');
      if (!step) return;
      // Controls of hidden groups are disabled so they are skipped by validation and the message.
      const groupHidden = [...form.querySelectorAll('[data-show-for], [data-hide-once]')].some(
        (node) => node.hidden && node.contains(control)
      );
      control.disabled = groupHidden;
    });
  };

  const setError = (field, key) => {
    const error = field.querySelector('[data-error]');
    field.classList.toggle('has-error', Boolean(key));
    field.querySelectorAll('input, select, textarea').forEach((control) => {
      if (key) control.setAttribute('aria-invalid', 'true');
      else control.removeAttribute('aria-invalid');
    });
    if (!error) return;
    if (key) {
      error.dataset.errorKey = key;
      error.textContent = copy()[key] || '';
      error.hidden = false;
    } else {
      delete error.dataset.errorKey;
      error.textContent = '';
      error.hidden = true;
    }
  };

  const validateField = (field) => {
    const rule = field.dataset.required || '';
    const control = field.querySelector('input:not([type="radio"]):not([type="checkbox"]), select, textarea');
    const value = control ? control.value.trim() : '';
    if (rule === 'choice') {
      return field.querySelector('input:checked') ? '' : 'formErrChoose';
    }
    if (rule === 'select') return value ? '' : 'formErrChoose';
    if (rule === 'phone') {
      if (!value) return 'formErrRequired';
      return normalizePhone(value) ? '' : 'formErrPhone';
    }
    if (rule === 'number') {
      if (!value) return 'formErrRequired';
      return positiveInteger(value) ? '' : 'formErrNumber';
    }
    if (rule === 'text') return value ? '' : 'formErrRequired';
    if (field.dataset.kind === 'number' && value) return nonNegativeInteger(value) ? '' : 'formErrNumber';
    return '';
  };

  const validateStep = (number) => {
    const step = steps[number - 1];
    let firstInvalid = null;
    step.querySelectorAll('.field').forEach((field) => {
      if (!isActiveField(field)) {
        setError(field, '');
        return;
      }
      const key = validateField(field);
      setError(field, key);
      if (key && !firstInvalid) firstInvalid = field;
    });
    summary.hidden = !firstInvalid;
    if (firstInvalid) {
      const control = firstInvalid.querySelector('input, select, textarea');
      control?.focus();
    }
    return !firstInvalid;
  };

  const showStep = (number, { focus = true } = {}) => {
    current = number;
    steps.forEach((step, index) => {
      step.hidden = index !== number - 1;
    });
    progress.forEach((item, index) => {
      const position = index + 1;
      item.classList.toggle('is-current', position === number);
      item.classList.toggle('is-done', position < number);
      if (position === number) item.setAttribute('aria-current', 'step');
      else item.removeAttribute('aria-current');
    });
    summary.hidden = true;
    if (focus) {
      const heading = steps[number - 1].querySelector('.quote-step-title');
      form.scrollIntoView({ block: 'start', behavior: 'smooth' });
      heading?.focus({ preventScroll: true });
    }
  };

  const readValue = (field) => {
    const choices = [...field.querySelectorAll('input[type="radio"]:checked, input[type="checkbox"]:checked')];
    if (choices.length) return choices.map((input) => input.closest('label').textContent.trim()).join(', ');
    if (field.querySelector('input[type="radio"], input[type="checkbox"]')) return '';
    const select = field.querySelector('select');
    if (select) return select.value ? select.options[select.selectedIndex].textContent.trim() : '';
    const control = field.querySelector('input, textarea');
    if (!control) return '';
    const value = control.value.trim().replace(/\s+/g, ' ');
    if (field.dataset.required === 'phone') return normalizePhone(value) || value;
    return value;
  };

  const composeMessage = () => {
    const text = copy();
    const lines = [text.msgIntro || 'Adal Works', ''];
    form.querySelectorAll('.field').forEach((field) => {
      if (!isActiveField(field) || field.closest('[data-quote-done]')) return;
      const control = field.querySelector('input, select, textarea');
      if (control && control.disabled) return;
      const value = readValue(field);
      if (!value) return;
      const label = text[field.dataset.label] || field.dataset.field;
      lines.push(`${label}: ${value}`);
    });
    lines.push('');
    lines.push(`${text.msgPage || 'Page'}: adalworks.kz${window.location.pathname}`);
    const tag = attributionTag();
    if (tag) lines.push(tag);
    return lines.join('\n');
  };

  // Hide the error summary once every highlighted field of the current step is fixed.
  const syncSummary = () => {
    if (!summary || summary.hidden) return;
    if (!steps[current - 1]?.querySelector('.field.has-error')) summary.hidden = true;
  };

  const applyPreset = () => {
    const preset = form.dataset.presetType;
    if (!preset) return;
    const input = form.querySelector(`input[name="type"][value="${preset}"]`);
    if (input) input.checked = true;
  };

  form.addEventListener('change', (event) => {
    if (event.target.name === 'type' || event.target.name === 'frequency') updateConditional();
    const field = event.target.closest('.field');
    if (field && field.classList.contains('has-error')) setError(field, validateField(field));
    syncSummary();
  });

  form.addEventListener('input', (event) => {
    const field = event.target.closest('.field');
    if (field && field.classList.contains('has-error') && !validateField(field)) setError(field, '');
    syncSummary();
  });

  form.querySelectorAll('[data-next]').forEach((button) => {
    button.addEventListener('click', () => {
      if (validateStep(current)) showStep(current + 1);
    });
  });

  form.querySelectorAll('[data-back]').forEach((button) => {
    button.addEventListener('click', () => showStep(current - 1));
  });

  form.addEventListener('keydown', (event) => {
    // Enter in a text field moves to the next step instead of submitting early.
    if (event.key === 'Enter' && event.target.tagName === 'INPUT' && current < steps.length) {
      event.preventDefault();
      if (validateStep(current)) showStep(current + 1);
    }
  });

  form.addEventListener('submit', (event) => {
    event.preventDefault();
    if (current < steps.length) {
      if (validateStep(current)) showStep(current + 1);
      return;
    }
    if (!validateStep(current)) return;
    lastUrl = whatsappUrl(composeMessage());
    doneLink.href = lastUrl;
    window.open(lastUrl, '_blank', 'noopener');
    steps.forEach((step) => {
      step.hidden = true;
    });
    progress.forEach((item) => {
      item.classList.remove('is-current');
      item.classList.add('is-done');
      item.removeAttribute('aria-current');
    });
    if (requiredNote) requiredNote.style.display = 'none';
    done.hidden = false;
    done.focus();
    form.dispatchEvent(new CustomEvent('quote:submitted', { bubbles: true, detail: { url: lastUrl } }));
  });

  form.querySelector('[data-restart]')?.addEventListener('click', () => {
    form.reset();
    applyPreset();
    updateConditional();
    form.querySelectorAll('.field').forEach((field) => setError(field, ''));
    done.hidden = true;
    if (requiredNote) requiredNote.style.display = '';
    showStep(1);
  });

  applyPreset();
  updateConditional();
  showStep(1, { focus: false });

  return {
    refresh() {
      form.querySelectorAll('[data-error]').forEach((error) => {
        if (error.dataset.errorKey) error.textContent = copy()[error.dataset.errorKey] || '';
      });
    },
    composeMessage,
  };
};

// ------------------------------------------------------------- start
captureAttribution();
document.querySelectorAll('[data-quote-form]').forEach((form) => quoteForms.push(initQuoteForm(form)));

const urlLanguage = (() => {
  try {
    return languageFromTag(new URLSearchParams(window.location.search).get('lang') || '');
  } catch {
    return '';
  }
})();

if (urlLanguage) setLanguage(urlLanguage, { persist: true });
else setLanguage(readSavedLanguage() || detectLanguage());
