# -*- coding: utf-8 -*-
"""All site texts. Each value is (ru, kz, en).

Rule: only facts confirmed on the current site or by Asset (see PR description).
"""

COMMON = {
    # navigation
    "navServices": ("Услуги", "Қызметтер", "Services"),
    "navServicesAll": ("Все услуги", "Барлық қызметтер", "All services"),
    "navZhk": ("ЖК, ОСИ и УК", "ТҮК, МИБ және БК", "Residential complexes & HOAs"),
    "navBc": ("Бизнес-центры и офисы", "Бизнес-орталықтар мен кеңселер", "Business centers & offices"),
    "navParking": ("Паркинги", "Паркингтер", "Parking"),
    "navTerritory": ("Территория и снег", "Аумақ және қар", "Grounds & snow"),
    "navHow": ("Как мы работаем", "Жұмыс тәртібі", "How we work"),
    "navQuote": ("Расчёт стоимости", "Құнын есептеу", "Get a quote"),
    "navTraining": ("Обучение и аудит", "Оқыту және аудит", "Training & Audit"),
    "navAbout": ("О нас", "Біз туралы", "About"),
    "navContact": ("Контакты", "Байланыс", "Contact"),
    "navAria": ("Основная навигация", "Негізгі навигация", "Main navigation"),
    "menuOpen": ("Открыть меню", "Мәзірді ашу", "Open menu"),
    "langAria": ("Выбор языка", "Тілді таңдау", "Choose language"),
    "whatsappFloatLabel": ("Написать в WhatsApp", "WhatsApp-қа жазу", "Message us on WhatsApp"),
    "crumbHome": ("Главная", "Басты бет", "Home"),
    "crumbAria": ("Навигационная цепочка", "Навигация тізбегі", "Breadcrumb"),

    # CTAs
    "ctaQuote": ("Узнать стоимость в WhatsApp", "Құнын WhatsApp арқылы білу", "Get a price on WhatsApp"),
    "ctaCall": ("Позвонить: +7 700 333 0 999", "Қоңырау шалу: +7 700 333 0 999", "Call: +7 700 333 0 999"),
    "ctaForm": ("Рассчитать стоимость онлайн", "Құнын онлайн есептеу", "Get a quote online"),
    "heroNote": (
        "Бесплатный осмотр объекта · Работаем по договору · Безналичный расчёт",
        "Нысанды тегін қарау · Шарт бойынша жұмыс · Қолма-қол ақшасыз есеп айырысу",
        "Free site visit · Contract-based · Cashless payment",
    ),
    "moreLink": ("Подробнее", "Толығырақ", "Learn more"),

    # how we work (5 steps)
    "stepsTag": ("Как мы работаем", "Жұмыс тәртібі", "How we work"),
    "stepsTitle": (
        "От заявки до работы на объекте — 5 шагов",
        "Өтінімнен нысандағы жұмысқа дейін — 5 қадам",
        "From request to work on site — 5 steps",
    ),
    "step1Title": ("Заявка", "Өтінім", "Request"),
    "step1Text": (
        "Пишете в WhatsApp, звоните или заполняете форму на сайте.",
        "WhatsApp-қа жазасыз, қоңырау шаласыз немесе сайттағы форманы толтырасыз.",
        "Message us on WhatsApp, call, or fill in the form on the site.",
    ),
    "step2Title": ("Бесплатный осмотр", "Тегін қарау", "Free site visit"),
    "step2Text": (
        "Смотрим объект на месте: площадь, зоны и задачи. Осмотр бесплатный.",
        "Нысанды орнында қараймыз: ауданы, аймақтары және міндеттері. Қарау тегін.",
        "We look at the site in person: area, zones and tasks. The visit is free.",
    ),
    "step3Title": ("Коммерческое предложение", "Коммерциялық ұсыныс", "Commercial proposal"),
    "step3Text": (
        "Рассчитываем стоимость по параметрам вашего объекта.",
        "Нысаныңыздың параметрлері бойынша құнын есептейміз.",
        "We calculate the price based on your site's parameters.",
    ),
    "step4Title": ("Договор", "Шарт", "Contract"),
    "step4Text": (
        "При подтверждении заключаем договор. Оплата — по безналичному расчёту.",
        "Сіз келіскен соң шарт жасаймыз. Төлем — қолма-қол ақшасыз есеп айырысу арқылы.",
        "Once you confirm, we sign a contract. Payment is cashless.",
    ),
    "step5Title": ("Работа на объекте", "Нысандағы жұмыс", "Work on site"),
    "step5Text": (
        "Выходим на объект по согласованному графику и отвечаем за результат.",
        "Келісілген кесте бойынша жұмысқа шығамыз және нәтижеге жауап береміз.",
        "We start on the agreed schedule and take responsibility for the result.",
    ),

    # formats
    "formatsTag": ("Форматы работы", "Жұмыс форматтары", "Service formats"),
    "formatsTitle": (
        "Под ключ или аутстаффинг",
        "Толық қызмет немесе аутстаффинг",
        "Turnkey or outstaffing",
    ),
    "formatsLead": (
        "В обоих форматах на объекте работает наш персонал. Подбор сотрудников и выход на смену — наша ответственность.",
        "Екі форматта да нысанда біздің персонал жұмыс істейді. Қызметкерлерді іріктеу және ауысымға шығуы — біздің жауапкершілігіміз.",
        "In both formats our staff work on site. Hiring and shift attendance are our responsibility.",
    ),
    "fmtColItem": ("Кто обеспечивает", "Кім қамтамасыз етеді", "Who provides"),
    "fmtColTurnkey": ("Под ключ", "Толық қызмет (под ключ)", "Turnkey"),
    "fmtColOut": ("Аутстаффинг", "Аутстаффинг", "Outstaffing"),
    "fmtRowStaff": ("Персонал на объекте", "Нысандағы персонал", "Staff on site"),
    "fmtRowHiring": ("Подбор персонала и выход на смену", "Персоналды іріктеу және ауысымға шығу", "Hiring and shift attendance"),
    "fmtRowChem": ("Химия", "Химия", "Cleaning chemicals"),
    "fmtRowTools": ("Инвентарь", "Құрал-сайман", "Cleaning tools"),
    "fmtRowEquip": ("Оборудование", "Жабдық", "Equipment"),
    "fmtRowFit": ("Подходит, если", "Қашан ыңғайлы", "Best when"),
    "fmtCellAw": ("Adal Works", "Adal Works", "Adal Works"),
    "fmtCellClient": ("Заказчик", "Тапсырыс беруші", "Client"),
    "fmtCellDiscuss": ("Уточняем при расчёте", "Есептеу кезінде нақтылаймыз", "Agreed when quoting"),
    "fmtFitTurnkey": (
        "Хотите передать уборку полностью одному подрядчику",
        "Тазалауды толығымен бір мердігерге бергіңіз келсе",
        "You want to hand over cleaning entirely to one contractor",
    ),
    "fmtFitOut": (
        "У вас уже есть своё оборудование и инвентарь",
        "Сізде өз жабдығыңыз бен құрал-сайманыңыз бар болса",
        "You already have your own equipment and tools",
    ),
    "fmtCta": (
        "Не знаете, какой формат выбрать? Подскажем на бесплатном осмотре.",
        "Қай форматты таңдарыңызды білмейсіз бе? Тегін қарау кезінде кеңес береміз.",
        "Not sure which format fits? We will advise during the free site visit.",
    ),

    # pricing parameters (confirmed by Asset)
    "priceZhkTitle": ("Жилой комплекс", "Тұрғын үй кешені", "Residential complex"),
    "priceZhk1": ("Количество подъездов", "Кіреберістер саны", "Number of entrances"),
    "priceZhk2": ("Этажность каждого подъезда", "Әр кіреберістің қабат саны", "Floors in each entrance"),
    "priceZhk3": ("Машиноместа в паркинге", "Паркингтегі машина орындары", "Parking spaces"),
    "priceZhk4": ("Периодичность уборки", "Тазалау жиілігі", "Cleaning frequency"),
    "priceComTitle": ("Коммерческий объект", "Коммерциялық нысан", "Commercial site"),
    "priceCom1": ("Площадь", "Ауданы", "Area"),
    "priceCom2": ("Этажность", "Қабат саны", "Number of floors"),
    "priceCom3": ("Количество санузлов", "Санитариялық тораптар саны", "Number of restrooms"),
    "priceCom4": ("Тип покрытия пола", "Еден жабынының түрі", "Floor covering type"),

    # shared FAQ
    "faqTag": ("Вопросы", "Сұрақтар", "Questions"),
    "faqTitle": ("Частые вопросы", "Жиі қойылатын сұрақтар", "Frequently asked questions"),
    "qFreeQ": ("Осмотр объекта платный?", "Нысанды қарау ақылы ма?", "Is the site visit paid?"),
    "qFreeA": (
        "Нет, осмотр бесплатный. После осмотра рассчитываем коммерческое предложение, а при вашем подтверждении заключаем договор.",
        "Жоқ, қарау тегін. Қараудан кейін коммерциялық ұсыныс есептейміз, ал сіз келіскен соң шарт жасаймыз.",
        "No, the visit is free. After it we prepare a commercial proposal, and once you confirm we sign a contract.",
    ),
    "qPayQ": ("Как происходит оплата?", "Төлем қалай жүреді?", "How does payment work?"),
    "qPayA": (
        "Работаем по договору, оплата — по безналичному расчёту.",
        "Шарт бойынша жұмыс істейміз, төлем — қолма-қол ақшасыз есеп айырысу арқылы.",
        "We work under a contract, and payment is cashless.",
    ),
    "qFormatsQ": (
        "Чем «под ключ» отличается от аутстаффинга?",
        "Толық қызметтің аутстаффингтен айырмашылығы неде?",
        "What is the difference between turnkey and outstaffing?",
    ),
    "qFormatsA": (
        "Под ключ — наш персонал, химия, инвентарь и оборудование. Аутстаффинг — наш персонал работает на вашем оборудовании и с вашим инвентарём, а подбор сотрудников и выход на смену остаются на нас.",
        "Толық қызмет — біздің персонал, химия, құрал-сайман және жабдық. Аутстаффинг — біздің персонал сіздің жабдығыңыз бен құрал-сайманыңызбен жұмыс істейді, ал қызметкерлерді іріктеу мен ауысымға шығуы бізде қалады.",
        "Turnkey means our staff, chemicals, tools and equipment. With outstaffing our staff work with your equipment and tools, while hiring and shift attendance remain our responsibility.",
    ),
    "qParkingQ": ("Как вы убираете паркинги?", "Паркингтерді қалай тазалайсыздар?", "How do you clean parking areas?"),
    "qParkingA": (
        "Механизированно — поломоечными машинами.",
        "Механикаландырылған тәсілмен — еден жуғыш машиналармен.",
        "Mechanically, with scrubber-dryer machines.",
    ),
    "qSnowQ": (
        "Убираете ли вы снег ночью и в выходные?",
        "Қарды түнде және демалыс күндері тазалайсыздар ма?",
        "Do you remove snow at night and on weekends?",
    ),
    "qSnowA": (
        "В сезон снегоуборка работает 24/7: дворы, парковки, пешеходные зоны, обработка реагентами.",
        "Маусымда қар тазалау 24/7 жұмыс істейді: аулалар, тұрақтар, жаяу жүргіншілер аймақтары, реагенттермен өңдеу.",
        "In season, snow removal runs 24/7: yards, parking areas, walkways and de-icing.",
    ),

    # related
    "relatedTitle": ("Другие услуги", "Басқа қызметтер", "Other services"),

    # contact / footer
    "contactTag": ("Контакты", "Байланыс", "Contact"),
    "contactTitle": (
        "Пригласите нас на бесплатный осмотр",
        "Бізді нысанды тегін қарауға шақырыңыз",
        "Invite us for a free site visit",
    ),
    "contactLead": (
        "Готовы обсудить долгосрочный договор на комплексное обслуживание нескольких объектов. Специальные условия для ОСИ и управляющих компаний.",
        "Бірнеше нысанға кешенді қызмет шартын талқылауға дайынбыз. МИБ (Мүлік иелерінің бірлестігі) және басқарушы компаниялар үшін арнайы шарттар.",
        "Ready to discuss a long-term contract for multiple facilities. Special terms for HOAs and property managers.",
    ),
    "phoneLabel": ("Телефон / WhatsApp / Telegram", "Телефон / WhatsApp / Telegram", "Phone / WhatsApp / Telegram"),
    "cityLabel": ("Город", "Қала", "City"),
    "cityValue": ("Астана, Казахстан", "Астана, Қазақстан", "Astana, Kazakhstan"),
    "hoursLabel": ("Режим работы", "Жұмыс уақыты", "Working hours"),
    "footerText": ("© 2026 Adal Works · Астана, Казахстан", "© 2026 Adal Works · Астана, Қазақстан", "© 2026 Adal Works · Astana, Kazakhstan"),
    "footerServices": ("Услуги", "Қызметтер", "Services"),
    "footerCompany": ("Компания", "Компания", "Company"),
    "footerContacts": ("Контакты", "Байланыс", "Contact"),
    "whatsappText": (
        "Здравствуйте, Adal Works! Хочу обсудить клининг для объекта.",
        "Сәлеметсіз бе, Adal Works! Нысанға клининг қызметін талқылағым келеді.",
        "Hello, Adal Works! I would like to discuss cleaning services for a facility.",
    ),
}

# ------------------------------------------------------------------ quote form
FORM = {
    "formTag": ("Расчёт стоимости", "Құнын есептеу", "Get a quote"),
    "formTitle": ("Рассчитать стоимость уборки", "Тазалау құнын есептеу", "Get a cleaning quote"),
    "formLead": (
        "Три коротких шага. Ответы соберутся в одно сообщение в WhatsApp, и вы отправите его сами. Точную стоимость назовём в коммерческом предложении после бесплатного осмотра.",
        "Үш қысқа қадам. Жауаптарыңыз WhatsApp-тағы бір хабарламаға жиналады, оны өзіңіз жібересіз. Нақты құнын тегін қараудан кейін коммерциялық ұсыныста айтамыз.",
        "Three short steps. Your answers are collected into one WhatsApp message that you send yourself. We give the exact price in a commercial proposal after a free site visit.",
    ),
    "formPoint1": ("Осмотр объекта бесплатный", "Нысанды қарау тегін", "The site visit is free"),
    "formPoint2": ("Работаем по договору", "Шарт бойынша жұмыс істейміз", "We work under a contract"),
    "formPoint3": ("Безналичный расчёт", "Қолма-қол ақшасыз есеп айырысу", "Cashless payment"),
    "formStepWord": ("Шаг", "Қадам", "Step"),
    "formStepOf": ("из 3", "/ 3", "of 3"),
    "formStep1Name": ("Объект", "Нысан", "Site"),
    "formStep2Name": ("Параметры", "Параметрлер", "Details"),
    "formStep3Name": ("Контакты", "Байланыс", "Contacts"),
    "formStep1Title": ("Какой у вас объект?", "Нысаныңыз қандай?", "What kind of site?"),
    "formStep2Title": ("Параметры объекта", "Нысан параметрлері", "Site details"),
    "formStep3Title": ("Как с вами связаться", "Сізбен қалай байланысамыз", "How can we reach you?"),
    "formType": ("Тип объекта", "Нысан түрі", "Type of site"),
    "formTypeZhk": ("ЖК / ОСИ", "ТҮК / МИБ", "Residential complex / HOA"),
    "formTypeBc": ("Бизнес-центр / офис", "Бизнес-орталық / кеңсе", "Business center / office"),
    "formTypeParking": ("Паркинг", "Паркинг", "Parking"),
    "formTypeTerritory": ("Территория / снег", "Аумақ / қар", "Grounds / snow"),
    "formTypeOther": ("Другое", "Басқа", "Other"),
    "formFreq": ("Как часто нужна уборка", "Тазалау қаншалықты жиі керек", "How often"),
    "formFreqRegular": ("Регулярно", "Тұрақты", "Regularly"),
    "formFreqOnce": ("Разово", "Бір рет", "One-time"),
    "formFormat": ("Формат работы", "Жұмыс форматы", "Service format"),
    "formFormatTurnkey": ("Под ключ", "Толық қызмет (под ключ)", "Turnkey"),
    "formFormatOut": ("Аутстаффинг", "Аутстаффинг", "Outstaffing"),
    "formFormatUnsure": ("Не знаю, посоветуйте", "Білмеймін, кеңес беріңіз", "Not sure, advise me"),
    "formFormatHint": (
        "Под ключ — наш персонал, химия, инвентарь и оборудование. Аутстаффинг — наш персонал на вашем оборудовании.",
        "Толық қызмет — біздің персонал, химия, құрал-сайман және жабдық. Аутстаффинг — сіздің жабдығыңыздағы біздің персонал.",
        "Turnkey: our staff, chemicals, tools and equipment. Outstaffing: our staff on your equipment.",
    ),
    "formEntrances": ("Количество подъездов", "Кіреберістер саны", "Number of entrances"),
    "formFloors": ("Этажность каждого подъезда", "Әр кіреберістің қабат саны", "Floors in each entrance"),
    "formFloorsHint": ("Например: 9, 9, 12, 16", "Мысалы: 9, 9, 12, 16", "For example: 9, 9, 12, 16"),
    "formSpaces": ("Машиномест в паркинге", "Паркингтегі машина орындары", "Parking spaces"),
    "formSpacesHint": ("Если паркинга нет, оставьте пустым", "Паркинг болмаса, бос қалдырыңыз", "Leave empty if there is no parking"),
    "formPeriod": ("Периодичность уборки", "Тазалау жиілігі", "Cleaning frequency"),
    "formChoose": ("Выберите", "Таңдаңыз", "Choose"),
    "formPeriodDaily": ("Ежедневно", "Күн сайын", "Daily"),
    "formPeriodSeveral": ("Несколько раз в неделю", "Аптасына бірнеше рет", "Several times a week"),
    "formPeriodWeekly": ("Раз в неделю", "Аптасына бір рет", "Once a week"),
    "formPeriodOther": ("Другое, напишу в комментарии", "Басқа, түсініктемеде жазамын", "Other, I will explain in the comment"),
    "formArea": ("Площадь, м²", "Ауданы, м²", "Area, m²"),
    "formStoreys": ("Этажность", "Қабат саны", "Number of floors"),
    "formRestrooms": ("Количество санузлов", "Санитариялық тораптар саны", "Number of restrooms"),
    "formCover": ("Тип покрытия пола", "Еден жабынының түрі", "Floor covering"),
    "formCoverTile": ("Плитка / керамогранит", "Плитка / керамогранит", "Tile / porcelain stoneware"),
    "formCoverLino": ("Линолеум / ПВХ", "Линолеум / ПВХ", "Linoleum / vinyl"),
    "formCoverCarpet": ("Ковролин", "Кілем жабыны", "Carpet"),
    "formCoverConcrete": ("Наливной пол / бетон", "Құйма еден / бетон", "Poured floor / concrete"),
    "formCoverMixed": ("Смешанное", "Аралас", "Mixed"),
    "formCoverUnknown": ("Не знаю", "Білмеймін", "Not sure"),
    "formParkingArea": ("Площадь паркинга, м² (если известна)", "Паркинг ауданы, м² (белгілі болса)", "Parking area, m² (if known)"),
    "formTerritoryArea": ("Площадь территории, м² (если известна)", "Аумақ ауданы, м² (белгілі болса)", "Grounds area, m² (if known)"),
    "formSeason": ("Что нужно", "Не қажет", "What you need"),
    "formSeasonWinter": ("Зимой — уборка снега", "Қыста — қар тазалау", "Winter — snow removal"),
    "formSeasonSummer": ("Летом — стрижка и полив газонов", "Жазда — көгалды шабу және суару", "Summer — mowing and watering"),
    "formSeasonYear": ("Уборка территории круглый год", "Аумақты жыл бойы тазалау", "Year-round grounds cleaning"),
    "formAddress": ("Адрес или район", "Мекенжайы немесе ауданы", "Address or district"),
    "formAddressHint": ("Астана, район или улица", "Астана, аудан немесе көше", "Astana, district or street"),
    "formStart": ("Когда начать", "Қашан бастау керек", "When to start"),
    "formStartAsap": ("Как можно скорее", "Мүмкіндігінше тез", "As soon as possible"),
    "formStartMonth": ("В течение месяца", "Бір ай ішінде", "Within a month"),
    "formStartSeason": ("К сезону", "Маусымға дейін", "Before the season"),
    "formStartPlan": ("Пока планирую", "Әзірге жоспарлап жүрмін", "Just planning"),
    "formRole": ("Кто вы", "Сіз кімсіз", "You are"),
    "formRoleOsi": ("ОСИ", "МИБ", "HOA"),
    "formRoleUk": ("Управляющая компания", "Басқарушы компания", "Property management company"),
    "formRoleOwner": ("Собственник", "Меншік иесі", "Owner"),
    "formRoleTenant": ("Арендатор", "Жалға алушы", "Tenant"),
    "formRoleOther": ("Другое", "Басқа", "Other"),
    "formName": ("Имя", "Атыңыз", "Name"),
    "formPhone": ("Телефон", "Телефон", "Phone"),
    "formPhoneHint": ("Например: +7 700 000 00 00", "Мысалы: +7 700 000 00 00", "For example: +7 700 000 00 00"),
    "formCompany": ("Компания или ОСИ", "Компания немесе МИБ", "Company or HOA"),
    "formComment": ("Комментарий", "Түсініктеме", "Comment"),
    "formOptional": ("необязательно", "міндетті емес", "optional"),
    "formRequiredNote": ("* — обязательные поля", "* — міндетті өрістер", "* — required fields"),
    "formNext": ("Далее", "Келесі", "Next"),
    "formBack": ("Назад", "Артқа", "Back"),
    "formSubmit": ("Отправить в WhatsApp", "WhatsApp-қа жіберу", "Send via WhatsApp"),
    "formNote": (
        "После нажатия откроется WhatsApp с готовым сообщением на номер +7 700 333 0 999. Сайт никуда больше не отправляет ваши данные.",
        "Батырманы басқанда +7 700 333 0 999 нөміріне дайын хабарламасы бар WhatsApp ашылады. Сайт деректеріңізді басқа ешқайда жібермейді.",
        "WhatsApp will open with a ready message to +7 700 333 0 999. The site does not send your data anywhere else.",
    ),
    "formErrRequired": ("Заполните это поле", "Осы өрісті толтырыңыз", "Please fill in this field"),
    "formErrChoose": ("Выберите вариант", "Нұсқаны таңдаңыз", "Please choose an option"),
    "formErrPhone": (
        "Проверьте номер, например: +7 700 000 00 00",
        "Нөмірді тексеріңіз, мысалы: +7 700 000 00 00",
        "Check the number, e.g. +7 700 000 00 00",
    ),
    "formErrNumber": ("Введите число больше нуля", "Нөлден үлкен сан енгізіңіз", "Enter a number greater than zero"),
    "formErrSummary": ("Проверьте отмеченные поля", "Белгіленген өрістерді тексеріңіз", "Please check the highlighted fields"),
    "formDoneTitle": ("Сообщение готово", "Хабарлама дайын", "Your message is ready"),
    "formDoneText": (
        "Мы открыли WhatsApp с вашими ответами, осталось нажать «Отправить». Если WhatsApp не открылся, нажмите кнопку ниже.",
        "Жауаптарыңыз бар WhatsApp аштық, «Жіберу» батырмасын басу ғана қалды. WhatsApp ашылмаса, төмендегі батырманы басыңыз.",
        "We opened WhatsApp with your answers, just tap Send. If WhatsApp did not open, use the button below.",
    ),
    "formDoneButton": ("Открыть WhatsApp", "WhatsApp-ты ашу", "Open WhatsApp"),
    "formRestart": ("Заполнить заново", "Қайта толтыру", "Start over"),
    "msgIntro": (
        "Здравствуйте, Adal Works! Заявка на расчёт стоимости с сайта.",
        "Сәлеметсіз бе, Adal Works! Сайттан құнын есептеуге өтінім.",
        "Hello, Adal Works! Quote request from the website.",
    ),
    "msgPage": ("Страница", "Бет", "Page"),
}

# ------------------------------------------------------------------ home page
HOME = {
    "heroTitle": (
        "Клининг для бизнес-центров, офисов и ЖК в Астане",
        "Астанадағы бизнес-орталықтар, кеңселер мен ТҮК үшін клининг",
        "Cleaning for business centers, offices and residential complexes in Astana",
    ),
    "heroTitleAccent": ("— один подрядчик на весь объект", "— бүкіл нысанға бір мердігер", "— one contractor for the whole site"),
    "heroLead": (
        "Уборка помещений, мойка паркингов, территория и снегоуборка по одному договору. 80 сотрудников, 21 объект на ежедневном обслуживании.",
        "Үй-жайларды тазалау, паркингтерді жуу, аумақ пен қарды тазалау — бір шарт бойынша. 80 қызметкер, күн сайын 21 нысан.",
        "Interior cleaning, parking washing, grounds and snow removal under one contract. 80 staff, 21 sites served daily.",
    ),
    "cycleTitle": ("Полный цикл — один договор", "Толық цикл — бір шарт", "Full cycle — one contract"),
    "cycleItem1": ("Помещения", "Үй-жайлар", "Interiors"),
    "cycleItem2": ("Паркинг", "Паркинг", "Parking"),
    "cycleItem3": ("Двор и территория", "Аула және аумақ", "Yard and grounds"),
    "cycleItem4": ("Снегоуборка", "Қар тазалау", "Snow removal"),
    "quoteWhatsapp": (
        "Здравствуйте, Adal Works! Хочу узнать стоимость уборки. Объект: ___, адрес: ___.",
        "Сәлеметсіз бе, Adal Works! Тазалау құнын білгім келеді. Нысан: ___, мекенжайы: ___.",
        "Hello, Adal Works! I'd like to know the cost of cleaning. Site: ___, address: ___.",
    ),

    # full cycle
    "fullTag": ("Полный цикл", "Толық цикл", "Full cycle"),
    "fullTitle": ("Полный цикл — один договор", "Толық цикл — бір шарт", "Full cycle — one contract"),
    "fullLead": (
        "Один подрядчик на весь объект: помещения, паркинг и прилегающая территория круглый год. Один договор и безналичный расчёт.",
        "Бүкіл нысанға бір мердігер: үй-жайлар, паркинг және жыл бойы іргелес аумақ. Бір шарт және қолма-қол ақшасыз есеп айырысу.",
        "One contractor for the whole site: interiors, parking and adjacent grounds all year round. One contract and cashless payment.",
    ),
    "full1Title": ("Помещения", "Үй-жайлар", "Interiors"),
    "full1Text": (
        "Подъезды, лифты, офисы, лестницы и места общего пользования.",
        "Кіреберістер, лифттер, кеңселер, сатылар және ортақ аймақтар.",
        "Entrances, elevators, offices, stairs and common areas.",
    ),
    "full2Title": ("Паркинг", "Паркинг", "Parking"),
    "full2Text": (
        "Механизированная уборка поломоечными машинами.",
        "Еден жуғыш машиналармен механикаландырылған тазалау.",
        "Mechanized cleaning with scrubber-dryer machines.",
    ),
    "full3Title": ("Территория летом", "Жазда аумақ", "Grounds in summer"),
    "full3Text": (
        "Подметание, вывоз мусора, стрижка и полив газонов.",
        "Сыпыру, қоқыс шығару, көгалды шабу және суару.",
        "Sweeping, waste removal, mowing and watering.",
    ),
    "full4Title": ("Снег зимой", "Қыста қар", "Snow in winter"),
    "full4Text": (
        "Уборка снега с дворов, парковок и пешеходных зон, реагенты, 24/7 в сезон.",
        "Аулалардан, тұрақтардан және жаяу жүргіншілер аймақтарынан қар тазалау, реагенттер, маусымда 24/7.",
        "Snow removal from yards, parking areas and walkways, de-icing, 24/7 in season.",
    ),

    # segments
    "segTag": ("Услуги", "Қызметтер", "Services"),
    "segTitle": ("Выберите тип объекта", "Нысан түрін таңдаңыз", "Choose your type of site"),
    "segLead": (
        "Для каждого типа объекта — своя страница: что входит, как считаем стоимость и ответы на частые вопросы.",
        "Әр нысан түріне жеке бет: не кіреді, құны қалай есептеледі және жиі қойылатын сұрақтарға жауаптар.",
        "Each type of site has its own page: what is included, how we price it and answers to common questions.",
    ),
    "segZhkTitle": ("ЖК, ОСИ и управляющие компании", "ТҮК, МИБ және басқарушы компаниялар", "Residential complexes, HOAs and property managers"),
    "segZhkText": (
        "Подъезды, лифты, паркинги, дворы и места общего пользования. Долгосрочные договоры с ОСИ и управляющими компаниями.",
        "Кіреберістер, лифттер, паркингтер, аулалар және ортақ аймақтар. МИБ және басқарушы компаниялармен ұзақ мерзімді шарттар.",
        "Entrances, elevators, parking, yards and common areas. Long-term contracts with HOAs and property managers.",
    ),
    "segBcTitle": ("Бизнес-центры и офисы", "Бизнес-орталықтар мен кеңселер", "Business centers and offices"),
    "segBcText": (
        "Ежедневная и периодическая уборка. Полы, окна, двери, лифты, поручни, лестницы. Вынос мусора по графику.",
        "Күнделікті және мерзімді тазалау. Еден, терезе, есік, лифт, тұтқа, сатылар. Кесте бойынша қоқыс шығару.",
        "Daily and periodic cleaning. Floors, windows, doors, elevators, handrails, stairs. Scheduled waste removal.",
    ),
    "segParkingTitle": ("Паркинги", "Паркингтер", "Parking"),
    "segParkingText": (
        "Механизированная уборка подземных паркингов поломоечными машинами.",
        "Жерасты паркингтерін еден жуғыш машиналармен механикаландырылған тазалау.",
        "Mechanized cleaning of underground parking with scrubber-dryer machines.",
    ),
    "segTerritoryTitle": ("Территория и снег", "Аумақ және қар", "Grounds and snow"),
    "segTerritoryText": (
        "Круглый год: зимой уборка снега и реагенты, летом стрижка и полив газонов, подметание и вывоз мусора.",
        "Жыл бойы: қыста қар тазалау және реагенттер, жазда көгалды шабу мен суару, сыпыру және қоқыс шығару.",
        "All year round: snow removal and de-icing in winter; mowing, watering, sweeping and waste removal in summer.",
    ),
    "segIndustrialTitle": ("Промышленный клининг", "Өнеркәсіптік клининг", "Industrial cleaning"),
    "segIndustrialText": (
        "Уборка промышленных объектов, складов, производственных помещений.",
        "Өнеркәсіптік нысандарды, қоймаларды, өндірістік үй-жайларды тазалау.",
        "Cleaning of industrial facilities, warehouses and production spaces.",
    ),

    # territory year-round
    "terrTag": ("Территория круглый год", "Жыл бойы аумақ", "Grounds all year"),
    "terrTitle": (
        "Прилегающая территория — круглый год",
        "Іргелес аумақ — жыл бойы",
        "Adjacent grounds — all year round",
    ),
    "terrLead": (
        "Зимой — снег, летом — зелёные насаждения. Одна команда и один договор на весь год.",
        "Қыста — қар, жазда — жасыл желек. Жыл бойы бір команда және бір шарт.",
        "Snow in winter, green areas in summer. One team and one contract for the whole year.",
    ),
    "terrWinterTitle": ("Зима", "Қыс", "Winter"),
    "terrWinterText": (
        "Оперативная уборка снега с дворов, парковок, пешеходных зон. Обработка реагентами. 24/7 в сезон.",
        "Аулалардан, тұрақтардан, жаяу жүргіншілер аймақтарынан қарды жедел тазалау. Реагенттермен өңдеу. Маусымда 24/7.",
        "Rapid snow removal from yards, parking areas and walkways. De-icing with reagents. 24/7 in season.",
    ),
    "terrSummerTitle": ("Лето", "Жаз", "Summer"),
    "terrSummerText": (
        "Уход за зелёными насаждениями: стрижка и полив газонов. Подметание и вывоз мусора.",
        "Жасыл желектерді күту: көгалды шабу және суару. Сыпыру және қоқыс шығару.",
        "Green area care: mowing and watering lawns. Sweeping and waste removal.",
    ),
    "terrMore": ("Подробнее о территории и снеге", "Аумақ пен қар туралы толығырақ", "More about grounds and snow"),

    # parking
    "parkTag": ("Паркинги", "Паркингтер", "Parking"),
    "parkTitle": ("Механизированная уборка паркингов", "Паркингтерді механикаландырылған тазалау", "Mechanized parking cleaning"),
    "parkText": (
        "Подземные паркинги жилых комплексов и бизнес-центров убираем поломоечными машинами. Паркинг можно включить в общий договор вместе с уборкой помещений и территории.",
        "Тұрғын үй кешендері мен бизнес-орталықтардың жерасты паркингтерін еден жуғыш машиналармен тазалаймыз. Паркингті үй-жайлар мен аумақты тазалаумен бірге ортақ шартқа қосуға болады.",
        "We clean underground parking of residential complexes and business centers with scrubber-dryer machines. Parking can be included in one contract together with interior and grounds cleaning.",
    ),
    "parkMore": ("Подробнее о паркингах", "Паркингтер туралы толығырақ", "More about parking"),
    "parkImgAlt": ("Поломоечная машина Adal Works", "Adal Works еден жуғыш машинасы", "Adal Works scrubber-dryer machine"),

    # pricing
    "priceTag": ("Стоимость", "Құны", "Pricing"),
    "priceTitle": ("Сколько стоит уборка вашего объекта", "Нысаныңызды тазалау қанша тұрады", "How much does cleaning your site cost"),
    "priceLead": (
        "Считаем по вашему объекту, а не «на глаз». Точную стоимость называем в коммерческом предложении после бесплатного осмотра. Для расчёта нам нужны:",
        "Құнды «көзбен шамалап» емес, нысаныңыз бойынша есептейміз. Нақты құнын тегін қараудан кейін коммерциялық ұсыныста айтамыз. Есептеу үшін бізге қажет:",
        "We price your actual site, not a guess. The exact price comes in a commercial proposal after a free site visit. To calculate, we need:",
    ),
    "priceButton": ("Отправить данные в WhatsApp", "Деректерді WhatsApp-қа жіберу", "Send details on WhatsApp"),
    "priceWhatsapp": (
        "Здравствуйте, Adal Works! Хочу узнать стоимость уборки. Объект: ___, адрес: ___.",
        "Сәлеметсіз бе, Adal Works! Тазалау құнын білгім келеді. Нысан: ___, мекенжайы: ___.",
        "Hello, Adal Works! I'd like to know the cost of cleaning. Site: ___, address: ___.",
    ),

    # home FAQ
    "faqPriceQ": ("Сколько стоит уборка?", "Тазалау қанша тұрады?", "How much does cleaning cost?"),
    "faqPriceA": (
        "Считаем по вашему объекту. Для ЖК — по количеству подъездов, этажности каждого подъезда, машиноместам в паркинге и периодичности уборки. Для коммерческих объектов — по площади, этажности, количеству санузлов и типу покрытия. Точную стоимость называем в коммерческом предложении после бесплатного осмотра.",
        "Нысаныңыз бойынша есептейміз. ТҮК үшін — кіреберістер саны, әр кіреберістің қабат саны, паркингтегі машина орындары және тазалау жиілігі бойынша. Коммерциялық нысандар үшін — ауданы, қабат саны, санитариялық тораптар саны және еден жабынының түрі бойынша. Нақты құнын тегін қараудан кейін коммерциялық ұсыныста айтамыз.",
        "We price your actual site. For residential complexes — by the number of entrances, floors in each entrance, parking spaces and cleaning frequency. For commercial sites — by area, number of floors, restrooms and floor covering type. The exact price comes in a commercial proposal after a free site visit.",
    ),
    "faqOsiQ": ("Работаете ли вы с ОСИ и управляющими компаниями?", "МИБ және басқарушы компаниялармен жұмыс істейсіздер ме?", "Do you work with HOAs and property managers?"),
    "faqOsiA": (
        "Да. Заключаем долгосрочные договоры с ОСИ и управляющими компаниями, для них есть специальные условия.",
        "Иә. МИБ және басқарушы компаниялармен ұзақ мерзімді шарттар жасаймыз, олар үшін арнайы шарттар бар.",
        "Yes. We sign long-term contracts with HOAs and property management companies, with special terms for them.",
    ),
    "faqOneQ": ("Можно ли передать всё одному подрядчику?", "Барлық жұмысты бір мердігерге тапсыруға бола ма?", "Can one contractor handle everything?"),
    "faqOneA": (
        "Да: уборка помещений, механизированная уборка паркинга поломоечными машинами и территория круглый год — зимой снег, летом стрижка и полив — по одному договору.",
        "Иә: үй-жайларды тазалау, паркингті еден жуғыш машиналармен механикаландырылған тазалау және жыл бойы аумақ — қыста қар, жазда шөп шабу мен суару — бір шарт бойынша.",
        "Yes: interior cleaning, mechanized parking cleaning with scrubber-dryers and year-round grounds care — snow in winter, mowing and watering in summer — under one contract.",
    ),
    "faqTrainingQ": ("Вы обучаете персонал?", "Персоналды оқытасыздар ма?", "Do you train your staff?"),
    "faqTrainingA": (
        "Да. Регулярные тренинги и сертификация, обучение на казахском и русском языках. Также проводим обучение и аудит клининга для сторонних команд.",
        "Иә. Тұрақты тренингтер мен сертификаттау өткіземіз, оқыту қазақ және орыс тілдерінде. Басқа командаларға да клининг бойынша оқыту мен аудит жүргіземіз.",
        "Yes. Regular training and certification, in Kazakh and Russian. We also provide cleaning training and audits for other teams.",
    ),
}

# ------------------------------------------------------------------ sub-pages
ZHK = {
    "pageTitle": (
        "Уборка ЖК в Астане для ОСИ и УК — подъезды, паркинг, двор | Adal Works",
        "Астанада ТҮК тазалау МИБ пен БК үшін — кіреберістер, паркинг, аула | Adal Works",
        "Residential complex cleaning in Astana for HOAs and property managers | Adal Works",
    ),
    "pageDescription": (
        "Уборка жилых комплексов в Астане по договору: подъезды, лифты, паркинг поломоечными машинами, двор круглый год. Бесплатный осмотр, безналичный расчёт. С 2018 года.",
        "Астанада тұрғын үй кешендерін шарт бойынша тазалау: кіреберістер, лифттер, паркингті еден жуғыш машиналармен тазалау, жыл бойы аула. Тегін қарау, қолма-қол ақшасыз есеп айырысу. 2018 жылдан.",
        "Contract cleaning of residential complexes in Astana: entrances, elevators, machine-cleaned parking, yards all year. Free site visit, cashless payment. Since 2018.",
    ),
    "schemaDescription": (
        "Уборка жилых комплексов в Астане для ОСИ и управляющих компаний: подъезды, лифты, места общего пользования, паркинг, двор круглый год.",
        "Астанада МИБ пен басқарушы компаниялар үшін тұрғын үй кешендерін тазалау: кіреберістер, лифттер, ортақ аймақтар, паркинг, жыл бойы аула.",
        "Residential complex cleaning in Astana for HOAs and property managers: entrances, elevators, common areas, parking, yards all year.",
    ),
    "pageHeroTag": ("Астана · Для ОСИ и управляющих компаний", "Астана · МИБ пен басқарушы компаниялар үшін", "Astana · For HOAs and property managers"),
    "pageH1": (
        "Уборка ЖК в Астане: подъезды, паркинг и двор по одному договору",
        "Астанада ТҮК тазалау: кіреберістер, паркинг пен аула бір шарт бойынша",
        "Residential complex cleaning in Astana: entrances, parking and yard under one contract",
    ),
    "pageLead": (
        "Долгосрочные договоры с ОСИ и управляющими компаниями, специальные условия. Наш персонал, механизированная уборка паркинга и территория круглый год: зимой снег, летом стрижка и полив.",
        "МИБ және басқарушы компаниялармен ұзақ мерзімді шарттар жасаймыз, олар үшін арнайы шарттар бар. Біздің персонал, паркингті механикаландырылған тазалау және жыл бойы аумақ: қыста қар, жазда шөп шабу мен суару.",
        "Long-term contracts with HOAs and property managers, with special terms. Our staff, mechanized parking cleaning and year-round grounds care: snow in winter, mowing and watering in summer.",
    ),
    "pageWhatsapp": (
        "Здравствуйте, Adal Works! Хочу узнать стоимость уборки ЖК. Подъездов: ___, этажность: ___, машиномест: ___.",
        "Сәлеметсіз бе, Adal Works! ТҮК тазалау құнын білгім келеді. Кіреберіс саны: ___, қабат саны: ___, машина орны: ___.",
        "Hello, Adal Works! I'd like a quote for a residential complex. Entrances: ___, floors: ___, parking spaces: ___.",
    ),
    "pageImgAlt": ("Уборка общих зон сотрудником Adal Works", "Adal Works қызметкері ортақ аймақты тазалауда", "Adal Works staff cleaning a common area"),
    "incTag": ("Что входит", "Не кіреді", "What is included"),
    "incTitle": ("Всё, что нужно дому, — у одного подрядчика", "Үйге қажеттінің бәрі — бір мердігерде", "Everything the building needs — from one contractor"),
    "inc1Title": ("Подъезды и лестницы", "Кіреберістер мен сатылар", "Entrances and stairs"),
    "inc1Text": ("Регулярная уборка подъездов, лестниц и мест общего пользования.", "Кіреберістерді, сатыларды және ортақ аймақтарды тұрақты тазалау.", "Regular cleaning of entrances, stairs and common areas."),
    "inc2Title": ("Лифты", "Лифттер", "Elevators"),
    "inc2Text": ("Уборка лифтов по согласованному графику.", "Лифттерді келісілген кесте бойынша тазалау.", "Elevator cleaning on an agreed schedule."),
    "inc3Title": ("Паркинг", "Паркинг", "Parking"),
    "inc3Text": ("Механизированная уборка подземного паркинга поломоечными машинами.", "Жерасты паркингін еден жуғыш машиналармен механикаландырылған тазалау.", "Mechanized cleaning of underground parking with scrubber-dryer machines."),
    "inc4Title": ("Двор зимой", "Қыста аула", "Yard in winter"),
    "inc4Text": ("Уборка снега, обработка реагентами, 24/7 в сезон.", "Қар тазалау, реагенттермен өңдеу, маусымда 24/7.", "Snow removal and de-icing, 24/7 in season."),
    "inc5Title": ("Двор летом", "Жазда аула", "Yard in summer"),
    "inc5Text": ("Подметание, вывоз мусора, стрижка и полив газонов.", "Сыпыру, қоқыс шығару, көгалды шабу және суару.", "Sweeping, waste removal, mowing and watering."),
    "inc6Title": ("Обученный персонал", "Оқытылған персонал", "Trained staff"),
    "inc6Text": ("Регулярные тренинги на казахском и русском языках.", "Қазақ және орыс тілдеріндегі тұрақты тренингтер.", "Regular training in Kazakh and Russian."),
    "pagePriceTitle": ("Как считаем стоимость уборки ЖК", "ТҮК тазалау құнын қалай есептейміз", "How we price residential complex cleaning"),
    "pagePriceLead": (
        "Стоимость зависит от параметров дома. Пришлите их — после бесплатного осмотра подготовим коммерческое предложение.",
        "Құны үйдің параметрлеріне байланысты. Оларды жіберіңіз — тегін қараудан кейін коммерциялық ұсыныс дайындаймыз.",
        "The price depends on the building's parameters. Send them to us, and after a free site visit we will prepare a commercial proposal.",
    ),
    "pq1Q": ("Что нужно для расчёта стоимости уборки ЖК?", "ТҮК тазалау құнын есептеу үшін не қажет?", "What do you need to price residential complex cleaning?"),
    "pq1A": (
        "Количество подъездов, этажность каждого подъезда, количество машиномест в паркинге и нужная периодичность уборки. Точную цену даём в коммерческом предложении после бесплатного осмотра.",
        "Кіреберістер саны, әр кіреберістің қабат саны, паркингтегі машина орындарының саны және қажетті тазалау жиілігі. Нақты бағаны тегін қараудан кейін коммерциялық ұсыныста береміз.",
        "The number of entrances, floors in each entrance, parking spaces and the cleaning frequency you need. We give the exact price in a commercial proposal after a free site visit.",
    ),
    "pq2Q": ("Работаете ли вы с ОСИ?", "МИБ-пен жұмыс істейсіздер ме?", "Do you work with HOAs?"),
    "pq2A": (
        "Да. Заключаем долгосрочные договоры с ОСИ и управляющими компаниями, для них есть специальные условия. Оплата — по безналичному расчёту.",
        "Иә. МИБ және басқарушы компаниялармен ұзақ мерзімді шарттар жасаймыз, олар үшін арнайы шарттар бар. Төлем — қолма-қол ақшасыз есеп айырысу арқылы.",
        "Yes. We sign long-term contracts with HOAs and property management companies, with special terms for them. Payment is cashless.",
    ),
    "pq3Q": ("Что вы делаете с двором зимой и летом?", "Қыста және жазда аулада не істейсіздер?", "What do you do with the yard in winter and summer?"),
    "pq3A": (
        "Зимой убираем снег с дворов, парковок и пешеходных зон и обрабатываем реагентами — 24/7 в сезон. Летом ухаживаем за газонами (стрижка и полив), подметаем и вывозим мусор.",
        "Қыста аулалардан, тұрақтардан және жаяу жүргіншілер аймақтарынан қар тазалап, реагенттермен өңдейміз — маусымда 24/7. Жазда көгалды күтеміз (шабу және суару), сыпырамыз және қоқыс шығарамыз.",
        "In winter we clear snow from yards, parking areas and walkways and apply de-icing — 24/7 in season. In summer we care for lawns (mowing and watering), sweep and remove waste.",
    ),
}

BC = {
    "pageTitle": (
        "Уборка бизнес-центров и офисов в Астане по договору | Adal Works",
        "Астанада бизнес-орталықтар мен кеңселерді шарт бойынша тазалау | Adal Works",
        "Business center and office cleaning in Astana | Adal Works",
    ),
    "pageDescription": (
        "Ежедневная и периодическая уборка бизнес-центров и офисов в Астане: полы, окна, двери, лифты, лестницы, вынос мусора по графику. Под ключ или аутстаффинг. Бесплатный осмотр, безналичный расчёт.",
        "Астанада бизнес-орталықтар мен кеңселерді күнделікті және мерзімді тазалау: еден, терезе, есік, лифт, сатылар, кесте бойынша қоқыс шығару. Толық қызмет немесе аутстаффинг. Тегін қарау, қолма-қол ақшасыз есеп айырысу.",
        "Daily and periodic cleaning of business centers and offices in Astana: floors, windows, doors, elevators, stairs, scheduled waste removal. Turnkey or outstaffing. Free site visit, cashless payment.",
    ),
    "schemaDescription": (
        "Уборка бизнес-центров и офисов в Астане по договору: ежедневная и периодическая уборка, форматы под ключ и аутстаффинг.",
        "Астанада бизнес-орталықтар мен кеңселерді шарт бойынша тазалау: күнделікті және мерзімді тазалау, толық қызмет және аутстаффинг форматтары.",
        "Contract cleaning of business centers and offices in Astana: daily and periodic cleaning, turnkey and outstaffing formats.",
    ),
    "pageHeroTag": ("Астана · Для бизнес-центров и офисов", "Астана · Бизнес-орталықтар мен кеңселер үшін", "Astana · For business centers and offices"),
    "pageH1": (
        "Уборка бизнес-центров и офисов в Астане",
        "Астанадағы бизнес-орталықтар мен кеңселерді тазалау",
        "Business center and office cleaning in Astana",
    ),
    "pageLead": (
        "Ежедневная и периодическая уборка по договору. Работаем под ключ — со своим персоналом, химией, инвентарём и оборудованием — или по аутстаффингу на вашем оборудовании.",
        "Шарт бойынша күнделікті және мерзімді тазалау. Толық қызмет форматында — өз персоналымызбен, химиямызбен, құрал-сайманымызбен және жабдығымызбен, немесе аутстаффинг форматында — сіздің жабдығыңызда жұмыс істейміз.",
        "Daily and periodic cleaning under contract. We work turnkey — with our own staff, chemicals, tools and equipment — or as outstaffing on your equipment.",
    ),
    "pageWhatsapp": (
        "Здравствуйте, Adal Works! Хочу узнать стоимость уборки офиса / БЦ. Площадь: ___ м², этажей: ___, санузлов: ___.",
        "Сәлеметсіз бе, Adal Works! Кеңсе / БО тазалау құнын білгім келеді. Ауданы: ___ м², қабат саны: ___, санторап саны: ___.",
        "Hello, Adal Works! I'd like a quote for office / business center cleaning. Area: ___ m², floors: ___, restrooms: ___.",
    ),
    "pageImgAlt": ("Сотрудник Adal Works моет окна", "Adal Works қызметкері терезе жууда", "Adal Works staff cleaning windows"),
    "incTag": ("Что входит", "Не кіреді", "What is included"),
    "incTitle": ("Уборка здания и всего, что вокруг", "Ғимаратты және айналасын тазалау", "Cleaning the building and everything around it"),
    "inc1Title": ("Помещения", "Үй-жайлар", "Premises"),
    "inc1Text": ("Полы, окна, двери, лифты, поручни, лестницы.", "Еден, терезе, есік, лифт, тұтқа, сатылар.", "Floors, windows, doors, elevators, handrails, stairs."),
    "inc2Title": ("Вынос мусора", "Қоқыс шығару", "Waste removal"),
    "inc2Text": ("По согласованному графику.", "Келісілген кесте бойынша.", "On an agreed schedule."),
    "inc3Title": ("Паркинг", "Паркинг", "Parking"),
    "inc3Text": ("Механизированная уборка поломоечными машинами.", "Еден жуғыш машиналармен механикаландырылған тазалау.", "Mechanized cleaning with scrubber-dryer machines."),
    "inc4Title": ("Территория", "Аумақ", "Grounds"),
    "inc4Text": ("Зимой уборка снега, летом стрижка и полив газонов.", "Қыста қар тазалау, жазда көгалды шабу және суару.", "Snow removal in winter, mowing and watering in summer."),
    "inc5Title": ("Склады и производство", "Қоймалар мен өндіріс", "Warehouses and production"),
    "inc5Text": ("Промышленный клининг складов и производственных помещений.", "Қоймалар мен өндірістік үй-жайлардың өнеркәсіптік клинингі.", "Industrial cleaning of warehouses and production spaces."),
    "inc6Title": ("Обученный персонал", "Оқытылған персонал", "Trained staff"),
    "inc6Text": ("Регулярные тренинги на казахском и русском языках.", "Қазақ және орыс тілдеріндегі тұрақты тренингтер.", "Regular training in Kazakh and Russian."),
    "pagePriceTitle": ("Как считаем стоимость уборки офиса и БЦ", "Кеңсе мен БО тазалау құнын қалай есептейміз", "How we price office and business center cleaning"),
    "pagePriceLead": (
        "Стоимость зависит от параметров здания. Пришлите их — после бесплатного осмотра подготовим коммерческое предложение.",
        "Құны ғимараттың параметрлеріне байланысты. Оларды жіберіңіз — тегін қараудан кейін коммерциялық ұсыныс дайындаймыз.",
        "The price depends on the building's parameters. Send them to us, and after a free site visit we will prepare a commercial proposal.",
    ),
    "pq1Q": ("Что нужно для расчёта стоимости уборки офиса?", "Кеңсе тазалау құнын есептеу үшін не қажет?", "What do you need to price office cleaning?"),
    "pq1A": (
        "Площадь, этажность, количество санузлов и тип покрытия пола. Точную цену даём в коммерческом предложении после бесплатного осмотра.",
        "Ауданы, қабат саны, санитариялық тораптар саны және еден жабынының түрі. Нақты бағаны тегін қараудан кейін коммерциялық ұсыныста береміз.",
        "The area, number of floors, number of restrooms and floor covering type. We give the exact price in a commercial proposal after a free site visit.",
    ),
    "pq2Q": ("Можно ли включить в договор паркинг и территорию?", "Шартқа паркинг пен аумақты қосуға бола ма?", "Can parking and grounds be included in the contract?"),
    "pq2A": (
        "Да. Уборку помещений, механизированную уборку паркинга и территорию круглый год можно объединить в одном договоре.",
        "Иә. Үй-жайларды тазалауды, паркингті механикаландырылған тазалауды және жыл бойы аумақты бір шартқа біріктіруге болады.",
        "Yes. Interior cleaning, mechanized parking cleaning and year-round grounds care can be combined in one contract.",
    ),
    "pq3Q": ("Убираете ли вы склады и производственные помещения?", "Қоймалар мен өндірістік үй-жайларды тазалайсыздар ма?", "Do you clean warehouses and production spaces?"),
    "pq3A": (
        "Да, это промышленный клининг: склады и производственные помещения.",
        "Иә, бұл өнеркәсіптік клининг: қоймалар мен өндірістік үй-жайлар.",
        "Yes, that is our industrial cleaning: warehouses and production spaces.",
    ),
}

PARKING = {
    "pageTitle": (
        "Уборка паркингов в Астане поломоечными машинами | Adal Works",
        "Астанада паркингтерді еден жуғыш машиналармен тазалау | Adal Works",
        "Parking cleaning in Astana with scrubber-dryers | Adal Works",
    ),
    "pageDescription": (
        "Механизированная уборка подземных паркингов ЖК и бизнес-центров в Астане поломоечными машинами. Зимой — уборка снега с открытых парковок. Бесплатный осмотр, договор, безналичный расчёт.",
        "Астанада ТҮК пен бизнес-орталықтардың жерасты паркингтерін еден жуғыш машиналармен механикаландырылған тазалау. Қыста — ашық тұрақтардан қар тазалау. Тегін қарау, шарт, қолма-қол ақшасыз есеп айырысу.",
        "Mechanized cleaning of underground parking for residential complexes and business centers in Astana with scrubber-dryers. Snow removal from open parking in winter. Free site visit, contract, cashless payment.",
    ),
    "schemaDescription": (
        "Механизированная уборка подземных паркингов поломоечными машинами в Астане.",
        "Астанада жерасты паркингтерін еден жуғыш машиналармен механикаландырылған тазалау.",
        "Mechanized cleaning of underground parking with scrubber-dryer machines in Astana.",
    ),
    "pageHeroTag": ("Астана · Паркинги ЖК и бизнес-центров", "Астана · ТҮК пен бизнес-орталықтардың паркингтері", "Astana · Parking for residential complexes and business centers"),
    "pageH1": ("Механизированная уборка паркингов в Астане", "Астанада паркингтерді механикаландырылған тазалау", "Mechanized parking cleaning in Astana"),
    "pageLead": (
        "Убираем подземные паркинги жилых комплексов и бизнес-центров поломоечными машинами. Паркинг можно объединить с уборкой здания и территории в одном договоре.",
        "Тұрғын үй кешендері мен бизнес-орталықтардың жерасты паркингтерін еден жуғыш машиналармен тазалаймыз. Паркингті ғимарат пен аумақты тазалаумен бір шартқа біріктіруге болады.",
        "We clean underground parking of residential complexes and business centers with scrubber-dryer machines. Parking can be combined with building and grounds cleaning in one contract.",
    ),
    "pageWhatsapp": (
        "Здравствуйте, Adal Works! Хочу узнать стоимость уборки паркинга. Машиномест: ___, периодичность: ___.",
        "Сәлеметсіз бе, Adal Works! Паркинг тазалау құнын білгім келеді. Машина орны: ___, жиілігі: ___.",
        "Hello, Adal Works! I'd like a quote for parking cleaning. Parking spaces: ___, frequency: ___.",
    ),
    "pageImgAlt": ("Поломоечная машина Adal Works", "Adal Works еден жуғыш машинасы", "Adal Works scrubber-dryer machine"),
    "incTag": ("Что входит", "Не кіреді", "What is included"),
    "incTitle": ("Паркинг — механизированно и по графику", "Паркинг — механикаландырылған және кесте бойынша", "Parking — mechanized and on schedule"),
    "inc1Title": ("Подземный паркинг", "Жерасты паркингі", "Underground parking"),
    "inc1Text": ("Механизированная уборка поломоечными машинами.", "Еден жуғыш машиналармен механикаландырылған тазалау.", "Mechanized cleaning with scrubber-dryer machines."),
    "inc2Title": ("Открытые парковки зимой", "Қыста ашық тұрақтар", "Open parking in winter"),
    "inc2Text": ("Уборка снега и обработка реагентами, 24/7 в сезон.", "Қар тазалау және реагенттермен өңдеу, маусымда 24/7.", "Snow removal and de-icing, 24/7 in season."),
    "inc3Title": ("Вместе с уборкой ЖК или БЦ", "ТҮК немесе БО тазалаумен бірге", "Together with complex or office cleaning"),
    "inc3Text": ("Один договор на помещения, паркинг и территорию.", "Үй-жайлар, паркинг және аумаққа бір шарт.", "One contract for interiors, parking and grounds."),
    "inc4Title": ("Профессиональная техника", "Кәсіби техника", "Professional machinery"),
    "inc4Text": ("Современная специализированная техника для любого типа объектов.", "Кез келген нысанға арналған заманауи арнайы техника.", "Modern specialized machinery for any facility type."),
    "pagePriceTitle": ("Что нужно для расчёта", "Есептеу үшін не қажет", "What we need for a quote"),
    "pagePriceLead": (
        "Пришлите эти данные — после бесплатного осмотра подготовим коммерческое предложение.",
        "Осы деректерді жіберіңіз — тегін қараудан кейін коммерциялық ұсыныс дайындаймыз.",
        "Send us these details, and after a free site visit we will prepare a commercial proposal.",
    ),
    "pp1": ("Тип объекта: ЖК или бизнес-центр", "Нысан түрі: ТҮК немесе бизнес-орталық", "Type of site: residential complex or business center"),
    "pp2": ("Количество машиномест", "Машина орындарының саны", "Number of parking spaces"),
    "pp3": ("Периодичность уборки", "Тазалау жиілігі", "Cleaning frequency"),
    "pq1Q": ("Что нужно для расчёта стоимости уборки паркинга?", "Паркинг тазалау құнын есептеу үшін не қажет?", "What do you need to price parking cleaning?"),
    "pq1A": (
        "Количество машиномест и периодичность уборки. Точную цену даём в коммерческом предложении после бесплатного осмотра.",
        "Машина орындарының саны және тазалау жиілігі. Нақты бағаны тегін қараудан кейін коммерциялық ұсыныста береміз.",
        "The number of parking spaces and the cleaning frequency. We give the exact price in a commercial proposal after a free site visit.",
    ),
    "pq2Q": ("Можно ли заказать паркинг вместе с уборкой ЖК или БЦ?", "Паркингті ТҮК немесе БО тазалаумен бірге тапсырыс беруге бола ма?", "Can parking be ordered together with complex or office cleaning?"),
    "pq2A": (
        "Да, по принципу «полный цикл — один договор»: помещения, паркинг и территория у одного подрядчика.",
        "Иә, «толық цикл — бір шарт» қағидасы бойынша: үй-жайлар, паркинг және аумақ бір мердігерде.",
        "Yes, following our «full cycle — one contract» approach: interiors, parking and grounds with one contractor.",
    ),
}

TERRITORY = {
    "pageTitle": (
        "Уборка территории и снега в Астане круглый год | Adal Works",
        "Астанада аумақ пен қарды жыл бойы тазалау | Adal Works",
        "Year-round grounds care and snow removal in Astana | Adal Works",
    ),
    "pageDescription": (
        "Прилегающая территория круглый год: зимой уборка снега и реагенты, 24/7 в сезон; летом стрижка и полив газонов, подметание, вывоз мусора. Для ЖК, БЦ и коммерческих объектов Астаны. Бесплатный осмотр.",
        "Іргелес аумақ жыл бойы: қыста қар тазалау және реагенттер, маусымда 24/7; жазда көгалды шабу мен суару, сыпыру, қоқыс шығару. Астанадағы ТҮК, БО және коммерциялық нысандар үшін. Тегін қарау.",
        "Adjacent grounds all year round: snow removal and de-icing in winter, 24/7 in season; mowing, watering, sweeping and waste removal in summer. For residential complexes, business centers and commercial sites in Astana. Free site visit.",
    ),
    "schemaDescription": (
        "Уборка прилегающей территории в Астане круглый год: снегоуборка и реагенты зимой, уход за газонами летом.",
        "Астанада іргелес аумақты жыл бойы тазалау: қыста қар тазалау мен реагенттер, жазда көгалды күту.",
        "Year-round grounds care in Astana: snow removal and de-icing in winter, lawn care in summer.",
    ),
    "pageHeroTag": ("Астана · Прилегающая территория", "Астана · Іргелес аумақ", "Astana · Adjacent grounds"),
    "pageH1": ("Уборка территории и снега в Астане круглый год", "Астанада аумақ пен қарды жыл бойы тазалау", "Year-round grounds care and snow removal in Astana"),
    "pageLead": (
        "Один подрядчик на прилегающую территорию в любое время года: зимой — снег и реагенты, летом — газоны, подметание и вывоз мусора.",
        "Іргелес аумаққа жылдың кез келген мезгілінде бір мердігер: қыста — қар мен реагенттер, жазда — көгал, сыпыру және қоқыс шығару.",
        "One contractor for your adjacent grounds in every season: snow and de-icing in winter; lawns, sweeping and waste removal in summer.",
    ),
    "pageWhatsapp": (
        "Здравствуйте, Adal Works! Хочу узнать стоимость уборки территории / снега. Адрес: ___, что нужно: ___.",
        "Сәлеметсіз бе, Adal Works! Аумақ / қар тазалау құнын білгім келеді. Мекенжайы: ___, не қажет: ___.",
        "Hello, Adal Works! I'd like a quote for grounds / snow removal. Address: ___, what is needed: ___.",
    ),
    "pageImgAlt": ("Инвентарь и техника Adal Works", "Adal Works құрал-сайманы мен техникасы", "Adal Works tools and machinery"),
    "incTag": ("Что входит", "Не кіреді", "What is included"),
    "incTitle": ("Зима и лето — по одному договору", "Қыс пен жаз — бір шарт бойынша", "Winter and summer — under one contract"),
    "inc1Title": ("Уборка снега", "Қар тазалау", "Snow removal"),
    "inc1Text": ("Оперативная уборка снега с дворов, парковок, пешеходных зон.", "Аулалардан, тұрақтардан, жаяу жүргіншілер аймақтарынан қарды жедел тазалау.", "Rapid snow removal from yards, parking areas and walkways."),
    "inc2Title": ("Антигололёд", "Көктайғаққа қарсы өңдеу", "De-icing"),
    "inc2Text": ("Обработка реагентами.", "Реагенттермен өңдеу.", "Treatment with reagents."),
    "inc3Title": ("24/7 в сезон", "Маусымда 24/7", "24/7 in season"),
    "inc3Text": ("Снегоуборка работает круглосуточно в снежный сезон.", "Қар маусымында қар тазалау тәулік бойы жұмыс істейді.", "Snow removal runs around the clock during the snow season."),
    "inc4Title": ("Газоны летом", "Жазда көгал", "Lawns in summer"),
    "inc4Text": ("Уход за зелёными насаждениями: стрижка и полив.", "Жасыл желектерді күту: шабу және суару.", "Green area care: mowing and watering."),
    "inc5Title": ("Чистая территория", "Таза аумақ", "Clean grounds"),
    "inc5Text": ("Подметание и вывоз мусора.", "Сыпыру және қоқыс шығару.", "Sweeping and waste removal."),
    "inc6Title": ("Круглый год", "Жыл бойы", "All year round"),
    "inc6Text": ("Круглогодичное обслуживание прилегающей территории.", "Іргелес аумаққа жыл бойы қызмет көрсету.", "Year-round maintenance of adjacent grounds."),
    "planTitle": ("Договоритесь до первого снега", "Бірінші қарға дейін келісіңіз", "Agree before the first snow"),
    "planText": (
        "Осмотрим территорию бесплатно и подготовим коммерческое предложение, чтобы договор можно было заключить заранее, до начала сезона.",
        "Аумақты тегін қарап, коммерциялық ұсыныс дайындаймыз, сонда шартты маусым басталғанға дейін алдын ала жасауға болады.",
        "We will inspect the grounds for free and prepare a commercial proposal, so the contract can be signed in advance, before the season starts.",
    ),
    "pagePriceTitle": ("Что нужно для расчёта", "Есептеу үшін не қажет", "What we need for a quote"),
    "pagePriceLead": (
        "Пришлите эти данные — после бесплатного осмотра подготовим коммерческое предложение.",
        "Осы деректерді жіберіңіз — тегін қараудан кейін коммерциялық ұсыныс дайындаймыз.",
        "Send us these details, and after a free site visit we will prepare a commercial proposal.",
    ),
    "tp1": ("Адрес и тип объекта", "Мекенжайы және нысан түрі", "Address and type of site"),
    "tp2": ("Зоны: дворы, парковки, пешеходные зоны, газоны", "Аймақтар: аулалар, тұрақтар, жаяу жүргіншілер аймақтары, көгалдар", "Zones: yards, parking areas, walkways, lawns"),
    "tp3": ("Сезон: зима, лето или круглый год", "Маусым: қыс, жаз немесе жыл бойы", "Season: winter, summer or all year round"),
    "pq1Q": ("Что входит в летний уход за территорией?", "Жазғы аумақ күтіміне не кіреді?", "What does summer grounds care include?"),
    "pq1A": (
        "Стрижка и полив газонов, подметание и вывоз мусора.",
        "Көгалды шабу және суару, сыпыру және қоқыс шығару.",
        "Mowing and watering lawns, sweeping and waste removal.",
    ),
    "pq2Q": ("Можно ли заключить договор на весь год?", "Бір жылға шарт жасауға бола ма?", "Can we sign a contract for the whole year?"),
    "pq2A": (
        "Да. Обслуживаем прилегающую территорию круглый год: зимой снег, летом зелёные насаждения.",
        "Иә. Іргелес аумаққа жыл бойы қызмет көрсетеміз: қыста қар, жазда жасыл желек.",
        "Yes. We maintain adjacent grounds all year round: snow in winter, green areas in summer.",
    ),
}
